name: CI
on: [push, pull_request]
jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-14
          - macos-15
          - macos-26
          - windows-2022
          - windows-2025
          - windows-2025-vs2026
        mode: [Debug, Release]
        compiler: [System, TinyCC]
        include:
          - os: ubuntu-22.04
            artifact_name: tocu-x86_64-ubuntu-22
          - os: ubuntu-24.04
            artifact_name: tocu-x86_64-ubuntu-24
          - os: macos-14
            artifact_name: tocu-arm64-macos-14
          - os: macos-15
            artifact_name: tocu-arm64-macos-15
          - os: macos-26
            artifact_name: tocu-arm64-macos-26
          - os: windows-2022
            artifact_name: tocu-x86_64-win32-2022-vs2022
          - os: windows-2025
            artifact_name: tocu-x86_64-win32-vs2022
          - os: windows-2025-vs2026
            artifact_name: tocu-x86_64-win32-vs2026
        exclude:
          - { os: macos-14, compiler: TinyCC }
          - { os: macos-15, compiler: TinyCC }
          - { os: macos-26, compiler: TinyCC }
          - os: windows-2022
            compiler: TinyCC
          - os: windows-2025
            compiler: TinyCC
          - os: windows-2025-vs2026
            compiler: TinyCC
    runs-on: ${{ matrix.os }}
    steps:
      - name: Dependencies
        if: ${{ matrix.compiler == 'TinyCC' }}
        run: |
          sudo apt-get update
          sudo apt-get -y install tcc
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.mode }}${{ matrix.compiler == 'TinyCC' && ' -DCMAKE_C_COMPILER=tcc' || '' }} -Bbuild
      - name: Build
        run: cmake --build build --config ${{ matrix.mode }}
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: ${{ format('{0}{1}{2}', matrix.artifact_name, matrix.compiler == 'TinyCC' && '-tcc' || '', matrix.mode == 'Debug' && '-debug' || '') }}
          path: ${{ startsWith(matrix.os, 'windows-') && format('build/{0}/*', matrix.mode) || 'build/tocu' }}
