on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
          - macos-26
          - macos-26-intel
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
          - windows-2025 # TODO(2026-07-12): Remove windows-2025 - *NOTICE: windows-2025 requests are being redirected to windows-2025-vs2026 by May 12, 2026*
          - windows-2025-vs2026
        mode:
          - Debug
          - Release
        cc:
          - clang-13
          - clang-14
          - clang-15
          - clang-16
          - clang-17
          - clang-18
          - clang-20
          - gcc-10
          - gcc-11
          - gcc-12
          - gcc-13
          - gcc-14
          - gcc-15
          - tcc
          - vs2022
          - vs2026
        exclude:
          - { os: macos-14, cc: clang-13 }
          - { os: macos-14, cc: clang-14 }
          - { os: macos-14, cc: clang-16 }
          - { os: macos-14, cc: clang-17 }
          - { os: macos-14, cc: clang-18 }
          - { os: macos-14, cc: clang-20 }
          - { os: macos-14, cc: gcc-10 }
          - { os: macos-14, cc: gcc-10 }
          - { os: macos-14, cc: gcc-11 }
          - { os: macos-14, cc: gcc-11 }
          - { os: macos-14, cc: gcc-12 }
          - { os: macos-14, cc: gcc-12 }
          - { os: macos-14, cc: tcc }
          - { os: macos-14, cc: vs2022 }
          - { os: macos-14, cc: vs2026 }
          - { os: macos-15-intel, cc: clang-13 }
          - { os: macos-15-intel, cc: clang-14 }
          - { os: macos-15-intel, cc: clang-15 }
          - { os: macos-15-intel, cc: clang-16 }
          - { os: macos-15-intel, cc: clang-20 }
          - { os: macos-15-intel, cc: gcc-10 }
          - { os: macos-15-intel, cc: gcc-11 }
          - { os: macos-15-intel, cc: gcc-12 }
          - { os: macos-15-intel, cc: tcc }
          - { os: macos-15-intel, cc: vs2022 }
          - { os: macos-15-intel, cc: vs2026 }
          - { os: macos-15, cc: clang-13 }
          - { os: macos-15, cc: clang-14 }
          - { os: macos-15, cc: clang-15 }
          - { os: macos-15, cc: clang-16 }
          - { os: macos-15, cc: clang-20 }
          - { os: macos-15, cc: gcc-10 }
          - { os: macos-15, cc: gcc-11 }
          - { os: macos-15, cc: gcc-12 }
          - { os: macos-15, cc: tcc }
          - { os: macos-15, cc: vs2022 }
          - { os: macos-15, cc: vs2026 }
          - { os: macos-26-intel, cc: clang-13 }
          - { os: macos-26-intel, cc: clang-14 }
          - { os: macos-26-intel, cc: clang-15 }
          - { os: macos-26-intel, cc: clang-16 }
          - { os: macos-26-intel, cc: clang-18 }
          - { os: macos-26-intel, cc: gcc-10 }
          - { os: macos-26-intel, cc: gcc-11 }
          - { os: macos-26-intel, cc: gcc-12 }
          - { os: macos-26-intel, cc: tcc }
          - { os: macos-26-intel, cc: vs2022 }
          - { os: macos-26-intel, cc: vs2026 }
          - { os: macos-26, cc: clang-13 }
          - { os: macos-26, cc: clang-14 }
          - { os: macos-26, cc: clang-15 }
          - { os: macos-26, cc: clang-16 }
          - { os: macos-26, cc: clang-18 }
          - { os: macos-26, cc: gcc-10 }
          - { os: macos-26, cc: gcc-11 }
          - { os: macos-26, cc: gcc-12 }
          - { os: macos-26, cc: tcc }
          - { os: macos-26, cc: vs2022 }
          - { os: macos-26, cc: vs2026 }
          - { os: ubuntu-22.04, cc: clang-16 }
          - { os: ubuntu-22.04, cc: clang-17 }
          - { os: ubuntu-22.04, cc: clang-18 }
          - { os: ubuntu-22.04, cc: clang-20 }
          - { os: ubuntu-22.04, cc: gcc-13 }
          - { os: ubuntu-22.04, cc: gcc-14 }
          - { os: ubuntu-22.04, cc: gcc-15 }
          - { os: ubuntu-22.04, cc: vs2022 }
          - { os: ubuntu-22.04, cc: vs2026 }
          - { os: ubuntu-24.04, cc: clang-13 }
          - { os: ubuntu-24.04, cc: clang-14 }
          - { os: ubuntu-24.04, cc: clang-15 }
          - { os: ubuntu-24.04, cc: clang-20 }
          - { os: ubuntu-24.04, cc: gcc-10 }
          - { os: ubuntu-24.04, cc: gcc-11 }
          - { os: ubuntu-24.04, cc: gcc-15 }
          - { os: ubuntu-24.04, cc: vs2022 }
          - { os: ubuntu-24.04, cc: vs2026 }
          - { os: windows-2022, cc: clang-13 }
          - { os: windows-2022, cc: clang-14 }
          - { os: windows-2022, cc: clang-15 }
          - { os: windows-2022, cc: clang-16 }
          - { os: windows-2022, cc: clang-17 }
          - { os: windows-2022, cc: clang-18 }
          - { os: windows-2022, cc: gcc-10 }
          - { os: windows-2022, cc: gcc-11 }
          - { os: windows-2022, cc: gcc-12 }
          - { os: windows-2022, cc: gcc-13 }
          - { os: windows-2022, cc: gcc-14 }
          - { os: windows-2022, cc: gcc-15 }
          - { os: windows-2022, cc: tcc }
          - { os: windows-2022, cc: vs2026 }
          - { os: windows-2025-vs2026, cc: clang-13 }
          - { os: windows-2025-vs2026, cc: clang-14 }
          - { os: windows-2025-vs2026, cc: clang-15 }
          - { os: windows-2025-vs2026, cc: clang-16 }
          - { os: windows-2025-vs2026, cc: clang-17 }
          - { os: windows-2025-vs2026, cc: clang-18 }
          - { os: windows-2025-vs2026, cc: gcc-10 }
          - { os: windows-2025-vs2026, cc: gcc-11 }
          - { os: windows-2025-vs2026, cc: gcc-12 }
          - { os: windows-2025-vs2026, cc: gcc-13 }
          - { os: windows-2025-vs2026, cc: gcc-14 }
          - { os: windows-2025-vs2026, cc: gcc-15 }
          - { os: windows-2025-vs2026, cc: tcc }
          - { os: windows-2025-vs2026, cc: vs2022 }
          - { os: windows-2025, cc: clang-13 }
          - { os: windows-2025, cc: clang-14 }
          - { os: windows-2025, cc: clang-15 }
          - { os: windows-2025, cc: clang-16 }
          - { os: windows-2025, cc: clang-17 }
          - { os: windows-2025, cc: clang-18 }
          - { os: windows-2025, cc: gcc-10 }
          - { os: windows-2025, cc: gcc-11 }
          - { os: windows-2025, cc: gcc-12 }
          - { os: windows-2025, cc: gcc-13 }
          - { os: windows-2025, cc: gcc-14 }
          - { os: windows-2025, cc: gcc-15 }
          - { os: windows-2025, cc: tcc }
          - { os: windows-2025, cc: vs2026 }

    runs-on: ${{ matrix.os }}
    steps:
      - name: Dependencies
        if: ${{ matrix.cc == 'tcc' }}
        run: |
          sudo apt-get update
          sudo apt-get -y install tcc
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.mode }}${{
          matrix.cc == 'clang-13' && ' -DCMAKE_C_COMPILER=clang-13'                                                                                                                                                            ||
          matrix.cc == 'clang-14' && ' -DCMAKE_C_COMPILER=clang-14'                                                                                                                                                            ||
          matrix.cc == 'clang-15' && (matrix.os == 'macos-14' && ' -DCMAKE_C_COMPILER=clang' || ' -DCMAKE_C_COMPILER=clang-15')                                                                                                ||
          matrix.cc == 'clang-16' && ' -DCMAKE_C_COMPILER=clang-16'                                                                                                                                                            ||
          matrix.cc == 'clang-17' && ((matrix.os == 'macos-15' || matrix.os == 'macos-15-intel' || matrix.os == 'macos-26' || matrix.os == 'macos-26-intel') && ' -DCMAKE_C_COMPILER=clang' || ' -DCMAKE_C_COMPILER=clang-17') ||
          matrix.cc == 'clang-18' && ((matrix.os == 'macos-15' || matrix.os == 'macos-15-intel') && ' -DCMAKE_C_COMPILER=$(brew --prefix llvm@18)/bin/clang' || ' -DCMAKE_C_COMPILER=clang-18')                                ||
          matrix.cc == 'clang-20' && ((matrix.os == 'macos-26' || matrix.os == 'macos-26-intel') && ' -DCMAKE_C_COMPILER=$(brew --prefix llvm@20)/bin/clang' || ' -DCMAKE_C_COMPILER=clang-20')                                ||
          matrix.cc == 'gcc-10'   && ' -DCMAKE_C_COMPILER=gcc-10'                                                                                                                                                              ||
          matrix.cc == 'gcc-11'   && ' -DCMAKE_C_COMPILER=gcc-11'                                                                                                                                                              ||
          matrix.cc == 'gcc-12'   && ' -DCMAKE_C_COMPILER=gcc-12'                                                                                                                                                              ||
          matrix.cc == 'gcc-13'   && ' -DCMAKE_C_COMPILER=gcc-13'                                                                                                                                                              ||
          matrix.cc == 'gcc-14'   && ' -DCMAKE_C_COMPILER=gcc-14'                                                                                                                                                              ||
          matrix.cc == 'gcc-15'   && ' -DCMAKE_C_COMPILER=gcc-15'                                                                                                                                                              ||
          matrix.cc == 'tcc'      && ' -DCMAKE_C_COMPILER=tcc'                                                                                                                                                                 ||
          ''
          }} -Bbuild
      - name: Build
        run: cmake --build build --config ${{ matrix.mode }}
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: ${{
            format(
            'tocu-{0}-{1}-{2}{3}',
            matrix.os,
            runner.arch,
            matrix.cc,
            matrix.mode == 'Debug' && '-debug' || ''
            )
            }}
          path: ${{ startsWith(matrix.os, 'windows-') && format('build/{0}/*', matrix.mode) || 'build/tocu' }}
